### PR TITLE
Fix compilation error by removing bad merge

### PR DESCRIPTION
**Pull request by markusthoemmes**
The 0.17.x line of upstream is still using pre 1.18 K8s dependencies, so there's no value in passing the context around everywhere just yet.

/assign @matzew @cardil

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by cardil** [comment]
Sorry about missing that
